### ISSUE TITLE
Add any script of your own.

### ISSUE THREAD

**Issue by acmpesuecc** [acmpesuecc/open_source_workshop#1]
Add in a file to the workshop folder with title as your name.
The file could contain any of the following things.

The document you made during the workshop
Any Script that you like (Any programming knowledge)
Any simple project of yours.
When Making a Pull request - make sure to add an appropriate commit.

**Comment by tgspsa** [comment]
[Akhil.txt](https://github.com/acmpesuecc/Workshop/files/3712270/Akhil.txt)

**Comment by ayushiawesome10** [comment]
[ayushi.txt](https://github.com/acmpesuecc/Workshop/files/3712275/ayushi.txt)

**Comment by lasya-priya-d** [comment]
no issues boi :))

**Comment by ThEcRAzYonE2169** [comment]
[shatakshi.txt](https://github.com/acmpesuecc/Workshop/files/3712278/shatakshi.txt)

**Comment by rkavya-coder** [comment]
[new.txt](https://github.com/acmpesuecc/Workshop/files/3712282/new.txt)
keerthana.txt

**Comment by shauryas1ngh** [comment]
[wksh.txt](https://github.com/acmpesuecc/Workshop/files/3712288/wksh.txt)

**Comment by mishranindya** [comment]
[Anindya.txt](https://github.com/acmpesuecc/Workshop/files/3712294/Anindya.txt)

**Comment by priyansh-jain10** [comment]
priyanshjain.txt

**Comment by meet1906** [comment]
[meet.txt](https://github.com/acmpesuecc/Workshop/files/3712301/meet.txt)
#include<stdio.h>
void main()
{
int i;
printf("HACKTOBER -- ACMPESU ECC");
for(i=1;i<=9;i++)
{
printf("9 DAYS TO GO:");
}
}

**Comment by Ramit-319** [comment]
ramit.txt

**Comment by harsha-source** [comment]
[w.txt](https://github.com/acmpesuecc/Workshop/files/3712325/w.txt)

**Comment by DarsiniDurai** [comment]
[DARSINI.txt](https://github.com/acmpesuecc/Workshop/files/3712342/DARSINI.txt)

**Comment by Naveennikhilesh** [comment]
[wk.txt](https://github.com/acmpesuecc/Workshop/files/3712352/wk.txt)
